// <auto-generated />
using System;
using CondominioMaster.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CondominioMaster.Infra.Data.Migrations
{
    [DbContext(typeof(ContextEFCondominioMaster))]
    [Migration("20190304205803_Criacao-tabela-Pessoa-relacionamento-Imovel")]
    partial class CriacaotabelaPessoarelacionamentoImovel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataIncluiRegistro")
                        .HasColumnType("DateTime");

                    b.Property<int>("IdCondominio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdCondominio");

                    b.ToTable("Edificacao");
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataIncluiRegistro")
                        .HasColumnType("DateTime");

                    b.Property<int>("IdEdificacao");

                    b.Property<int>("IdPessoaFinanceiro");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroPorta")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdEdificacao");

                    b.HasIndex("IdPessoaFinanceiro");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataIncluiRegistro")
                        .HasColumnType("DateTime");

                    b.Property<int>("IdEmpresa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataIncluiRegistro")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataIncluiRegistro")
                        .HasColumnType("DateTime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao", b =>
                {
                    b.HasOne("CondominioMaster.Domain.Entities.Condominio", "Condominio")
                        .WithMany("Edificacoes")
                        .HasForeignKey("IdCondominio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "CPFCNPJ", b1 =>
                        {
                            b1.Property<int>("EdificacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("CpfCnpj")
                                .HasColumnType("varchar(14)");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Edificacao");

                            b1.HasOne("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao")
                                .WithOne("CPFCNPJ")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "EdificacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "Email", b1 =>
                        {
                            b1.Property<int>("EdificacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Edificacao");

                            b1.HasOne("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao")
                                .WithOne("Email")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "EdificacaoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int>("EdificacaoId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnName("Cidade")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnName("Endereco")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Edificacao");

                            b1.HasOne("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao")
                                .WithOne("Endereco")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "EdificacaoId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "CEP", b2 =>
                                {
                                    b2.Property<int?>("EnderecoVOEdificacaoId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Codigo")
                                        .HasColumnName("CEP")
                                        .HasColumnType("varchar(8)");

                                    b2.ToTable("Edificacao");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("CEP")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "EnderecoVOEdificacaoId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "UF", b2 =>
                                {
                                    b2.Property<int?>("EnderecoVOEdificacaoId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF")
                                        .HasColumnType("varchar(2)");

                                    b2.ToTable("Edificacao");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("UF")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "EnderecoVOEdificacaoId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Imovel", b =>
                {
                    b.HasOne("CondominioMaster.Domain.Entities.AgregacaoEdificacao.Edificacao", "Edificacao")
                        .WithMany("Imoveis")
                        .HasForeignKey("IdEdificacao")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CondominioMaster.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Imoveis")
                        .HasForeignKey("IdPessoaFinanceiro")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Condominio", b =>
                {
                    b.HasOne("CondominioMaster.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Condominios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "CPFCNPJ", b1 =>
                        {
                            b1.Property<int>("CondominioId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("CpfCnpj")
                                .HasColumnType("varchar(14)");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Condominio");

                            b1.HasOne("CondominioMaster.Domain.Entities.Condominio")
                                .WithOne("CPFCNPJ")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "CondominioId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "Email", b1 =>
                        {
                            b1.Property<int>("CondominioId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Condominio");

                            b1.HasOne("CondominioMaster.Domain.Entities.Condominio")
                                .WithOne("Email")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "CondominioId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int>("CondominioId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnName("Cidade")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnName("Endereco")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Condominio");

                            b1.HasOne("CondominioMaster.Domain.Entities.Condominio")
                                .WithOne("Endereco")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "CondominioId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "CEP", b2 =>
                                {
                                    b2.Property<int>("EnderecoVOCondominioId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Codigo")
                                        .HasColumnName("CEP")
                                        .HasColumnType("varchar(8)");

                                    b2.ToTable("Condominio");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("CEP")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "EnderecoVOCondominioId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "UF", b2 =>
                                {
                                    b2.Property<int>("EnderecoVOCondominioId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF")
                                        .HasColumnType("varchar(2)");

                                    b2.ToTable("Condominio");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("UF")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "EnderecoVOCondominioId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Empresa", b =>
                {
                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "CPFCNPJ", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("CpfCnpj")
                                .HasColumnType("varchar(14)");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Empresa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Empresa")
                                .WithOne("CPFCNPJ")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "EmpresaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "Email", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Empresa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Empresa")
                                .WithOne("Email")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "EmpresaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnName("Cidade")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnName("Endereco")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Empresa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Empresa")
                                .WithOne("Endereco")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "EmpresaId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "CEP", b2 =>
                                {
                                    b2.Property<int>("EnderecoVOEmpresaId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Codigo")
                                        .HasColumnName("CEP")
                                        .HasColumnType("varchar(8)");

                                    b2.ToTable("Empresa");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("CEP")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "EnderecoVOEmpresaId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "UF", b2 =>
                                {
                                    b2.Property<int>("EnderecoVOEmpresaId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF")
                                        .HasColumnType("varchar(2)");

                                    b2.ToTable("Empresa");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("UF")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "EnderecoVOEmpresaId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });

            modelBuilder.Entity("CondominioMaster.Domain.Entities.Pessoa", b =>
                {
                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "CPFCNPJ", b1 =>
                        {
                            b1.Property<int?>("PessoaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnName("CpfCnpj")
                                .HasColumnType("varchar(14)");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("Pessoa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Pessoa")
                                .WithOne("CPFCNPJ")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CpfCnpjVO", "PessoaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "Email", b1 =>
                        {
                            b1.Property<int?>("PessoaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Pessoa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Pessoa")
                                .WithOne("Email")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EmailVO", "PessoaId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "Endereco", b1 =>
                        {
                            b1.Property<int?>("PessoaId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .HasColumnName("Bairro")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnName("Cidade")
                                .HasColumnType("varchar(30)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasColumnName("Endereco")
                                .HasColumnType("varchar(100)");

                            b1.ToTable("Pessoa");

                            b1.HasOne("CondominioMaster.Domain.Entities.Pessoa")
                                .WithOne("Endereco")
                                .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO", "PessoaId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "CEP", b2 =>
                                {
                                    b2.Property<int?>("EnderecoVOPessoaId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("Codigo")
                                        .HasColumnName("CEP")
                                        .HasColumnType("varchar(8)");

                                    b2.ToTable("Pessoa");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("CEP")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.CepVO", "EnderecoVOPessoaId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });

                            b1.OwnsOne("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "UF", b2 =>
                                {
                                    b2.Property<int?>("EnderecoVOPessoaId")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("UF")
                                        .HasColumnName("UF")
                                        .HasColumnType("varchar(2)");

                                    b2.ToTable("Pessoa");

                                    b2.HasOne("CondominioMaster.Domain.Shared.ValueObjects.EnderecoVO")
                                        .WithOne("UF")
                                        .HasForeignKey("CondominioMaster.Domain.Shared.ValueObjects.UfVO", "EnderecoVOPessoaId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
